// Códigos de idioma ISO 639-1 suportados pelo Whisper
export const LANGUAGES = [
  { code: 'auto', name: 'Detecção Automática (Idioma Original)' },
  { code: 'auto-translate', name: 'Detecção Automática (Traduzir para Inglês)' },
  { code: 'pt', name: 'Português' },
  { code: 'en', name: 'Inglês' },
  { code: 'es', name: 'Espanhol' },
  { code: 'zh', name: 'Chinês' },
  { code: 'de', name: 'Alemão' },
  { code: 'ru', name: 'Russo' },
  { code: 'ko', name: 'Coreano' },
  { code: 'fr', name: 'Francês' },
  { code: 'ja', name: 'Japonês' },
  { code: 'tr', name: 'Turco' },
  { code: 'pl', name: 'Polonês' },
  { code: 'ca', name: 'Catalão' },
  { code: 'nl', name: 'Holandês' },
  { code: 'ar', name: 'Árabe' },
  { code: 'sv', name: 'Sueco' },
  { code: 'it', name: 'Italiano' },
  { code: 'id', name: 'Indonésio' },
  { code: 'hi', name: 'Hindi' },
  { code: 'fi', name: 'Finlandês' },
  { code: 'vi', name: 'Vietnamita' },
  { code: 'he', name: 'Hebraico' },
  { code: 'uk', name: 'Ucraniano' },
  { code: 'el', name: 'Grego' },
  { code: 'ms', name: 'Malaio' },
  { code: 'cs', name: 'Tcheco' },
  { code: 'ro', name: 'Romeno' },
  { code: 'da', name: 'Dinamarquês' },
  { code: 'hu', name: 'Húngaro' },
  { code: 'ta', name: 'Tâmil' },
  { code: 'no', name: 'Norueguês' },
  { code: 'th', name: 'Tailandês' },
  { code: 'ur', name: 'Urdu' },
  { code: 'hr', name: 'Croata' },
  { code: 'bg', name: 'Búlgaro' },
  { code: 'lt', name: 'Lituano' },
];
